[bundle]
app_name=TextView+
app_msg=\sIf you don't like to read, you haven't  found the right book! - J.K Rowling
app_about=TextView+\n{version}\n2026\nPaul Hocker\n
dev_name=tvp-{version}-b{build}
dev_about=TextView+\n{version}\n2026\nb{build}\n
dev_msg=hello world
disk_type=d64
car_type=3
disk_build=1
car_build=1
car_note=TextView+ App
car_checksum=1
src_path=src
version=1.2

[build]
main.o=build.asm

[files]
;about.t=seq,about.txt
;msg.t=seq,msg.txt
main.o=prg,main.o
menu.m=seq,menu.txt
icon.charset=prg,icon.charset
readme.t=seq,readme.txt
